project:
  type: website
  output-dir: docs

website:
  title: "relearning-stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "記事一覧"
        href: posts.qmd
      - text: "コラム"
        href: column.qmd
      - text: "R"
        href: R.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



