project:
  type: website
  output-dir: docs

website:
  title: "relearning-stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "記事一覧"
        href: posts.qmd
      - text: "コラム"
        href: column.qmd
      - text: "R"
        href: R.qmd

metadata-files:
  - _metadata.yml

format:
  html:
    include-in-header: "meta.html"
    include-after-body: "ga.html"
    theme: litera
    highlight-style: a11y-dark
    code-block-border-left: "#3E8EDE"
    code-background: "#f8f9fa"
    code-line-numbers: true
    code-copy: true
    css: styles.css   # スタイルをcssで指定する





