baseURL: https://boss-kasai.github.io/relearning-stats/
languageCode: ja
title: Relearning Stats
theme: archie
copyright: © Athul
pygmentsstyle: monokai
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
params:
  mode: auto
  social:
    - icon: github
      name: GitHub
      url: https://github.com/boss-kasai
  subtitle: R・統計・Pythonの再学習ブログ
  useCDN: no
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: All posts
      url: /posts
      weight: 2
    - name: About
      url: /about
      weight: 3
    - name: Tags
      url: /tags
      weight: 4
ignoreErrors:
  - error-missing-instagram-accesstoken
