---
title: "ラボラトリー方式はラボを出られるか"
format: html
author: "ThePastOfDice"
date: '2025-04-23'
last-modified: "2025-04-27"
categories: ["コラム"]
tags: []
---

私は大学時代にラボラトリー方式の体験学習というものを授業で何度も体験しました。
それ自体は面白い経験でしたし、今でも価値が一定あったと思っています。
しかし、大学を卒業して社会に出てから違和感を感じる部分もありました。
大学自体の友人とラボラトリー方式の体験学習について話す機会があったので、そこで考えたこと・思ったことについてまとめてみました。

## ラボラトリー方式の体験学習とは何か
専門的な話は書籍などに任せますが、ラボラトリー方式の体験学習とは、 「**特別に設計された人と人とが関わる場 において、参加者自身の行動や関係性を素材にしながら、 そこでの体験を通し て人間関係を学ぶ方法**」です([出典](https://rci.nanzan-u.ac.jp/ninkan/publish/item/08_02_01.pdf))。
教科書などの教材があるわけではなく、特別に設計された人と人が関わる場(ラボ)での行動や感情などを題材に人間関係を学ぶわけです。人間関係といっていますが、自分自身について気づく場でもあります。
この説明だけではあまり分からないと思いますので、もう少し具体的に説明します。
基本的な流れは下記のような感じです。
- グループワーク
- 振り返り
- 振り返りの共有

まずは、就活でやるようなグループワークを行います。
グループワーク中はその中でワークと並行して、その中で起こっていることに注目します。
グループワーク後に、そのワーク中に何が起きていたのかを個人で振り返ります。
その後、振り返りの内容をグループで共有します。
グループワークの中で、誰かの言った一言が方向を決めたり、自然と役割分担がでたり、そう言ったグループ内で起きた動きや、誰かの言った発言で自分は発言しづらくなったとか、そう言った個人の中での感情の動きなども気付きになります。

このワーク自体は結構面白いと思います。

## ラボラトリー方式の体験学習のメリット
ここからは私が今考えるラボラトリー方式の体験学習の良かった点です。
一般的に言われていることと違っても、これは個人の感じたことなので許してください。

### 自分に敏感になれる
最も価値のあった成長は自分に感情に敏感になれたことです。意外と自分の気持ちについて気が付かないものです。
自分がイライラしているのか、悲しいのか、怒っているのか、そう言ったネガティブな感情を弁別するのは難しいことが多いです。それをリアルタイム、もしくは早い段階で検知できると他人との軋轢をある程度カバーすることができます。

### 挑戦的なことができる
ラボラトリー方式のいい部分は、日常から分離された環境であるからそこいつも自分がやらない挑戦的な姿勢を試すことができることです。
ワークの中では、ロールで指定されるものもあり、普段自分がやらないロールを実践することで道の自分を検証することができます。日常生活でやると「あいつキャラが変わった」みたいに思われることもあります。しかし、日常から切り離された環境だからこそ、新しい自分を試すことができます。

### 他者評価(フィードバック)を得られる
「自分の振る舞いが他者からどのように見られているのか」、実社会ではこの情報を得ることが難しいです。特に社会人になると、自分に耳の痛いことを言ってくれる人は少なくなります。気が合う人とは仲良くしますが、気が合わない人とは適度距離を置くようになります。年齢が上がるとさらに自分にフィードバックをくれる人は減ってしまいます。
ラボ内では、このフィードバックがたくさん得られることが大きなメリットでした。グループワーク中、自分が考え込んでしまっている時に、周りは私が不機嫌だったりネガティブな状況だと認識することがあるというのは、私の大きな気づきでした。自分のちょっとした癖が、意外と他者にとっては気になる仕草だったりします。

## 大学の授業での限界

### 譲れないものがない
私は人間関係の軋轢が生まれるのは、譲れないものがある時が多いのだと思ういます。ワークで何かタスクをこなす場合でも、そのタスクをこなす絶対的な必要性がないのです。仕事などでは売り上げへのコミットや自らの成果・責任などの影響を抱えています。家庭では、お金の使い方や子育てなどの譲れない問題があるでしょう。学生でも部活やクラス対抗の学園祭などがあれば、妥協できない強い気持ちがあるでしょう。
このようにタスク自体の優先度が高い場合、よりリアルな衝突が起きます。
しかし、ラボラトリーの中ではそこまで熱量のある問題を作ることができません。だからこそラボな部分はあると思うのですが。社会人がこのワークをやれば、普段はリスクなどの面から挑戦的な新しい姿勢やタスクに没頭してしまうことで見えない関係性(プロセス)をラボラトリーで見ることができると思います。しかし、学生が授業で集中的にラボラトリーをやっても、日常生活への汎用的な気づきにならないように思います。
学生時代にやったラボでの経験と、社会に出てからの実社会での気づきが別物として認識されてしまうのだと思います。

### 同質集団すぎた
大学でのラボラトリー方式の体験学習は、その参加者の多様性においてとても大きな問題を抱えていたと思います。年齢、学力、親の所得、育成環境がかなり同質な集団が大学には揃ってしまいます。特に、私のいた大学は9割程度は自宅からの通学生で地域的多様性もありませんでした。実社会に出ると、年齢、その集団での職務時間(職場での先輩後輩)、バックグラウンドの違う人たちと関わっていくことになります。
さらに取引先など利害関係も関わりかなり複雑になっていると思います。そう言ったものによる関係性の複雑さやアプローチの難しさは、大学時代はほとんど感じませんでした。
良くも悪くも”良い子”が集まっていたのだと思います。二日酔いで登場してワーク中に眠ったり、「今日はやる気がない」とサボる人もいませんでした。みんなある程度ワークの意図を理解して協力する前提で、ワークに参加します。前提条件が綺麗すぎるのだと思います。
もし今私が大学に戻るなら、ちょっと辺なことをしたいと思います。
また、年齢や状況が違う人たちとやってみたいとも思います。

### 相手にも多くの前提が共有されている

また実社会でグループや他者に対して働きかけるようとすると、ラボとは違い相手の受け止め方にも気をつけなければいけません。ラボ内では、働きかけることができても、現実社会ではちょっとした働きかけに、相手が「攻撃された」と認識されていうこともあります。これは、コミュニケーションの本質でもあると思います。コミュニケーションは基本的に発信者・受信者双方に大きな要因があります。発信者がIメッセージを意識しても、受信者がそういったコミュニケーションに慣れていないとキツく言われていると感じてしまうことがあります。
ラボ内では、送受信者双方がグループワークやその後のフィードバックに慣れています。そのため、働きかけがしやすいです。ちょっと踏み込んだ働きかけをしても相手が適宜受け取ってくれます。しかし、実社会にでてしまうとそう簡単ではありません。これは職場などではなく、パートナーとの関係でもそうだと思います。二人の間に起きる問題を向き合ってじっくり話し合える人もいれば、それが苦手で有耶無耶にしたい人もいると思います。
ラボ内では経験しなかった問題が実社会では起き、それが意外と深刻なのだと思います。「どのような働きかけをするか」という問題の中で「働きかける対象がどのように受け取るか」という問題がラボよりも高度な問題になります。

## ラボラトリー方式はラボを出られるか
私が感じていた主題「**ラボラトリー方式はラボを出られるか**」。

つまり、体験や学びがラボ特有のことになってしまい、実社会に適応できないのではないかということです。
ラボ自体は日常から離されたラボであることが大切です。日常から切り離されているからこそ、挑戦したりゆっくり考えたり日常でできないことができるのだと思います。それはタスクにおいても同じことが言えると思います。タスクに没入しすぎないことが、多くの気づきにつながるのだと思います。

しかしこの学習の本質は、ラボでの学びを日常にフィードバックするということだと思います。ラボでの学びを日常で実践することに価値があるのだと思います。ラボの中では、プロセスに目を向けられるし働きかけられるけど、日常ではそれが全くできないとなってしまうと、それは意味がなくなってしまうと思います。
ただこの問題は研究と社会実装に関する全ての領域に行ける問題だと思います。研究室内では複雑性を排除するために、環境などの要因を整えて1つの事象の研究するので、実社会にそれを適応しようとして時にその複雑性から簡単にはいきません。ラボラトリー方式でも同じことが起きているのかなと思います。参加者の属性や前提知識が整えられていることで、よりプロセスを見たり、働きかけたり、フィードバックをもらうことができます。そう言った意味で、ラボの価値があるのだと思います。ただ、実践的な学習であるからこそ実社会に活かすことができる方が価値があるのではないかとも思います。

私自身は大学自体のラボラトリー方式の学びを積極的に日常に活かしていると思います。
パートナーと対話する時間も意図的に作りますし、Iメッセージで伝えるようにもしています。
しかし、ラボでの学びを卒業生のどれほどの人数ができているのか。
大学時代の授業の時にもっとラボと日常を繋ぐための工夫はできないのか。
そんなことを考えています。

もし私の後輩がこの記事を読んでいたら、ラボでの学びを日常にどう生かせるのかなんて考えてみてほしいです。
学生なら、バイト先やサークルなど学科の授業ではない部分で何が実践できるのかを考え、実践してみてほしいです。
そして、ラボでは積極的に”いつも”じゃない自分を演じてみてほしいです。
そもそも大学自体が巨大なラボです。たくさん挑戦して失敗できる環境はとても貴重です。
ぜひ有効活用してみてください。